spring.application.name=todo-task-backend
spring.mvc.apiversion.use.header=API-Version
spring.mvc.apiversion.default=1

# DATASOURCE
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:127.0.0.1}:${POSTGRES_PORT:5432}/${POSTGRES_DB:postgres}
spring.datasource.username=${POSTGRES_USERNAME:postgres}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# LIQUIBASE
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml

# JWT
jwt.secret-key=${JWT_SECRET_KEY}
jwt.cookie.domain=${JWT_COOKIE_DOMAIN}

jwt.cookie.http-only=true
jwt.cookie.same-site=Lax

jwt.refresh.duration=31
jwt.refresh.duration-unit=DAYS

jwt.access.duration=15
jwt.access.duration-unit=MINUTES